import { describe, it, expect } from 'vitest';
import { deliverReport } from '../src/delivery.js';
import * as dotenv from 'dotenv';

dotenv.config();

describe('E2E Integration & Delivery (Phase 7.3)', () => {
  it('should successfully append to Google Docs and create a Gmail draft using the MCP server', async () => {
    // Skip if env vars aren't setup
    if (!process.env.MCP_SERVER_URL || !process.env.STAKEHOLDER_EMAIL || !process.env.GOOGLE_DOC_ID) {
      console.warn('Skipping E2E test due to missing environment variables.');
      return;
    }

    const testPayload = {
      top_critical_issues: ["Test Issue 1"],
      top_feature_requests: ["Test Feature 1"],
      quotes: ["Test Quote"],
      actionable_ideas: ["Test Idea"],
      email_summary: "This is a test summary generated by the automated E2E test suite to verify the MCP integration."
    };

    // Execute delivery
    const result = await deliverReport(testPayload);

    // Assert that the pipeline interacted with MCP properly
    expect(result.docsSuccess).toBe(true);
    expect(result.docsUrl).toContain(process.env.GOOGLE_DOC_ID);
    
    expect(result.gmailDraftSuccess).toBe(true);
    expect(result.gmailDraftId).toBeTruthy();
  }, 60000); // 60s timeout for remote network calls
});
