/**
 * Phase 5: MCP Integration — Google Docs & Gmail Delivery
 * 
 * This module uses the MCP client to:
 *   1. Append the full structured report to a Google Document (if GOOGLE_DOC_ID is configured)
 *   2. Create a Gmail draft with the ≤250-word email summary + Doc link
 * 
 * MCP Server Tools Used:
 *   - gdocs_append_content({ document_id: string, content: string })
 *   - gmail_create_draft({ to: string[], subject: string, body: string })
 */
import * as dotenv from 'dotenv';
import { MCPClient, isMCPError, type MCPToolResponse } from './mcp_client.js';

dotenv.config();

/** The structure produced by Phase 4 (analysis.ts → synthesizeThemes) */
export interface FinalReport {
  top_critical_issues: string[];
  top_feature_requests: string[];
  quotes: string[];
  actionable_ideas: string[];
  email_summary: string;
}

/** Result returned by the delivery pipeline */
export interface DeliveryResult {
  docsSuccess: boolean;
  docsUrl: string | null;
  gmailDraftSuccess: boolean;
  gmailDraftId: string | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Build a full markdown report from the final report JSON.
 * This is the content appended to Google Docs.
 */
function buildMarkdownReport(report: FinalReport): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  let md = '';
  md += `\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  md += `📊 Weekly Feedback Pulse — ${dateStr}\n`;
  md += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

  md += `🔴 TOP 3 CRITICAL ISSUES\n`;
  report.top_critical_issues.forEach((issue, i) => {
    md += `  ${i + 1}. ${issue}\n`;
  });

  md += `\n💡 TOP 3 FEATURE REQUESTS\n`;
  report.top_feature_requests.forEach((feature, i) => {
    md += `  ${i + 1}. ${feature}\n`;
  });

  md += `\n💬 VERBATIM USER QUOTES\n`;
  report.quotes.forEach((quote, i) => {
    md += `  ${i + 1}. "${quote}"\n`;
  });

  md += `\n🚀 ACTIONABLE IDEAS\n`;
  report.actionable_ideas.forEach((idea, i) => {
    md += `  ${i + 1}. ${idea}\n`;
  });

  md += `\n───────────────────────────────────────────\n`;

  return md;
}

/**
 * Build the email body (≤250 words summary + Doc link).
 */
function buildEmailBody(report: FinalReport, docsUrl: string | null): string {
  let body = '';
  body += `Hi Team,<br><br>`;
  body += `Here is this week's Feedback Pulse summary:<br><br>`;
  body += report.email_summary.replace(/\n/g, '<br>');
  body += `<br><br>`;

  if (docsUrl) {
    body += `📄 <a href="${docsUrl}">View Full Report in Google Docs</a><br><br>`;
  }

  body += `---<br><i>This report was auto-generated by the Mobile Store Feedback Pulse pipeline.</i><br>`;

  return body;
}

/**
 * Extract text content from an MCP tool response.
 */
function extractText(response: MCPToolResponse): string {
  if (isMCPError(response)) return '';
  return response.content
    .filter(c => c.type === 'text')
    .map(c => c.text)
    .join('\n');
}

// ─── Main Delivery Pipeline ──────────────────────────────────────────────────

export async function deliverReport(report: FinalReport): Promise<DeliveryResult> {
  const mcpServerUrl = process.env.MCP_SERVER_URL;
  if (!mcpServerUrl) {
    throw new Error('MCP_SERVER_URL is not set in .env');
  }

  const result: DeliveryResult = {
    docsSuccess: false,
    docsUrl: null,
    gmailDraftSuccess: false,
    gmailDraftId: null,
  };

  // Initialize MCP client
  const client = new MCPClient(mcpServerUrl);
  try {
    await client.connect();
  } catch (e: any) {
    console.error('[Delivery] Failed to connect to MCP server:', e.message);
    throw e;
  }

  try {
    // ──────────────────────────────────────────────────────────────
    // Step 5.1: Google Docs Delivery
    // ──────────────────────────────────────────────────────────────
    const googleDocId = process.env.GOOGLE_DOC_ID;
    
    if (googleDocId) {
      console.log('\n[Delivery] Step 5.1a: Clearing existing report in Google Doc...');
      const clearResponse = await client.callTool('gdocs_clear_content', {
        document_id: googleDocId,
      });

      if (isMCPError(clearResponse)) {
        console.warn('[Delivery] Google Docs Clear Error (this is expected if the server is not updated yet):', clearResponse.error);
      } else {
        const clearText = extractText(clearResponse);
        console.log('[Delivery] Google Docs clear response:', clearText);
      }

      console.log('\n[Delivery] Step 5.1b: Appending report to Google Doc...');
      const markdownReport = buildMarkdownReport(report);
      
      const docsResponse = await client.callTool('gdocs_append_content', {
        document_id: googleDocId,
        content: markdownReport,
      });

      if (isMCPError(docsResponse)) {
        console.error('[Delivery] Google Docs Error:', docsResponse.error);
        console.warn('[Delivery] Continuing with Gmail delivery...');
      } else {
        const docsText = extractText(docsResponse);
        console.log('[Delivery] Google Docs response:', docsText);
        result.docsSuccess = true;
        result.docsUrl = `https://docs.google.com/document/d/${googleDocId}/edit`;
        console.log(`[Delivery] ✅ Report appended to Google Doc: ${result.docsUrl}`);
      }
    } else {
      console.log('[Delivery] Step 5.1: Skipping Google Docs (GOOGLE_DOC_ID not configured in .env)');
      console.log('[Delivery] To enable: set GOOGLE_DOC_ID=<your-document-id> in .env');
    }

    // ──────────────────────────────────────────────────────────────
    // Step 5.2: Gmail Delivery
    // ──────────────────────────────────────────────────────────────
    const stakeholderEmail = process.env.STAKEHOLDER_EMAIL;
    
    if (!stakeholderEmail) {
      console.warn('[Delivery] Step 5.2: Skipping Gmail (STAKEHOLDER_EMAIL not configured in .env)');
      console.warn('[Delivery] To enable: set STAKEHOLDER_EMAIL=user@example.com in .env');
    } else {
      console.log('\n[Delivery] Step 5.2: Creating Gmail draft...');

      const now = new Date();
      const weekStr = now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
      const subject = `📊 Weekly Feedback Pulse — ${weekStr}`;
      const emailBody = buildEmailBody(report, result.docsUrl);

      // Split comma-separated emails into array
      const recipients = stakeholderEmail.split(',').map(e => e.trim()).filter(Boolean);

      const draftResponse = await client.callTool('gmail_create_draft', {
        to: recipients,
        subject: subject,
        body: emailBody,
      });

      if (isMCPError(draftResponse)) {
        console.error('[Delivery] Gmail Draft Error:', draftResponse.error);
      } else {
        const draftText = extractText(draftResponse);
        console.log('[Delivery] Gmail response:', draftText);

        // Parse draft ID from response text
        const draftIdMatch = draftText.match(/Draft ID:\s*(.+)/);
        result.gmailDraftId = draftIdMatch ? draftIdMatch[1]!.trim() : null;
        result.gmailDraftSuccess = true;
        console.log(`[Delivery] ✅ Gmail draft created successfully (Draft ID: ${result.gmailDraftId})`);
      }
    }
  } finally {
    await client.disconnect();
  }

  return result;
}
